apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: efogk8s
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        namespace: efogk8s
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        image: nginx:1.7.9
        ports:
        - containerPort: 80
