apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"drum-machine-deployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"drum-machine"}},"template":{"metadata":{"labels":{"app":"drum-machine"}},"spec":{"containers":[{"image":"efog/drum-machine-build-test:1","name":"drum-machine","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: 2019-05-16T19:20:13Z
  generation: 3
  name: drum-machine-deployment
  namespace: default
  resourceVersion: "14356"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/drum-machine-deployment
  uid: a0ef89b6-780f-11e9-8578-0800278bdbcf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: drum-machine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drum-machine
    spec:
      containers:
      - image: efog/drum-machine-build-test:1
        imagePullPolicy: IfNotPresent
        name: drum-machine
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2019-05-16T19:46:14Z
    lastUpdateTime: 2019-05-16T19:46:25Z
    message: ReplicaSet "drum-machine-deployment-76bdf7986c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-05-17T12:25:40Z
    lastUpdateTime: 2019-05-17T12:25:40Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
