apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodeapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}